{* Copyright (C) 2006  The University of Waikato
 *
 * This file is part of ccsweb - CRCnet Configuration System Web Interface
 *
 * Author:       Matt Brown <matt@crc.net.nz>
 * Version:      $Id$
 *
 * ccsweb is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * ccsweb is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * ccsweb; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *}
{include file="header.tpl" title="Changeset History"}
Each update in the configuration system is part of a changeset. Related changes
can be grouped into a single changeset for ease of management using the options
in the sidebar. Full history is maintained in the database for each changeset allowing an earlier configuration to be easily restored.<br />
<br />
Changesets are tightly integrated with the various configuration files that are
generated by the configuration system. Each time a configuration file (or set
of configuration files) is updated a new revision is created. This revision is
attached to the latest changeset available at the time.<br />
<br />
<form method="post" action="/?function=changesetHistory">
Start On:
{html_select_date start_year="2005" end_year="+1" field_order="DMY" time="$time"}
&nbsp;&nbsp;
and view
{html_options name="days" values=$daylist output=$daylist selected=$days}
days history
&nbsp;&nbsp;
<input type="submit" value="refresh" />
</form>
<br />
<table>
<tr>
    <th>Date</th>
    <th>User</th>
    <th width="40%">Description</th>
    <th>Revision No.</th>
</tr>
{foreach from=$changeset_hist item=cset}
<tr class="{cycle values="row1,row2"}">
    <td>{$cset.timestamp|date_format:"%H:%M %a %d %b %Y"}</td>
    <td>{$cset.username}</td>
    <td>{$cset.description|nl2br}</td>
    <td>
        <a href="/configs/?rev={$cset.svn_revision}">{$cset.svn_revision}</a>
    </td>
</tr>
{/foreach}
</table>
{include file="footer.tpl"}
