{* Copyright (C) 2006  The University of Waikato
 *
 * This file is part of ccsweb - CRCnet Configuration System Web Interface
 *
 * Graph manipulation interface
 *
 * Author:       Chris Browning <ckb6@cs.waikato.ac.nz>
 * Version:      $Id: rrdbot-props.tpl 1161 2006-12-01 01:39:43Z ckb6 $
 *
 * ccsweb is free software; you can redistribute it and/or modify it under the
 * terms of the GNU General Public License version 2 as published by the Free
 * Software Foundation.
 *
 * ccsweb is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * ccsweb; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *}
{include file="header.tpl" title="Graphs"}
<form name="filter" method="get" action="graph.php">
<input type="hidden" name="counttimer" value={$counttimer} id="counttimer"/>
</form>
<div id="instructions">
These tables are generated by the SNMP Discoverer automaticly.
<br>
{if $countstate == 1}
Currently running. Page refresh in 
{/if}
{if $countstate == 2}
Currently doing a full network probe. Page refresh in 
{/if}
{if  $countstate==0}
Next run in 
{/if}
<span id="Counter" name="counter"></span>.
<br />
<br />
<h2>Instructions</h2>
<br />
These instructions will be executed next run.
<table>
<tr>
    <th>Host</th>
    <th>Instruction</th>
    <th>Param1</th>
    <th>Param2</th>
    <th>Param3</th>
</tr>
{foreach from=$instrs item=instr}
<tr class="{cycle values="row1,row2"}">
    <td{$class}>{$instr.host_name}</td>
    <td{$class}>{$instr.instr_name}</td>
    <td{$class}>{$instr.param1}</td>
    <td{$class}>{$instr.param2}</td>
    <td{$class}>{$instr.param3}</td>
</tr>
{/foreach}
</table>
<br />
<h2>Logs</h2>
<br />
<font color=red>Warning:</font> Removing an entry here might remove the ability to view one or more graphs. Flushing this table will remove knowledge of ALL graphs.
<br />
<br />
<font color=red>Warning:</font> This table is auto generated by the SNMP Discoverer. It will find and add any new hosts every 5 minutes. It will examine the whole network once a night. This means that a removed valid entry might not be re-inserted until midnight!
</div>
<ul>
<li><a href="snmp-log.php?do=flush">Flush entire table</a></li>
</ul>
<table>
<tr>
    <th>Host</th>
    <th>Class</th>
    <th>ifDiscr</th>
    <th>IP Address</th>
    <th>Matched link</th>
    <th>Time</th>
    <th>Options</th>
</tr>
{foreach from=$entries item=entry}
<tr class="{cycle values="row1,row2"}">
    <td{$class}>{$entry.host_name}</td>
    <td{$class}>{$entry.class_name}</td>
    <td{$class}>{$entry.num}</td>
    <td{$class}>{$entry.ip_address}</td>
    <td{$class}>{$entry.description}</td>
    <td{$class}>{$entry.timestamp}</td>
    <td{$class}>
    <a href="snmp-log.php?do=delete&class_id={$entry.class_id}&host_id={$entry.host_id}&num={$entry.num}&host_name={$entry.host_name}&class_name={$entry.class_name}">[delete]</a>
    &nbsp;
    <a href="snmp-log.php?do=deletehost&host_id={$entry.host_id}&host_name={$entry.host_name}">[delete host's entries]</a>
    &nbsp;
    <a href="snmp-log.php?do=scanhost&host_id={$entry.host_id}">[re-probe host]</a>  
    </td>
</tr>
{/foreach}
</table>
<br />
<br />
{include file="footer.tpl"}
